{% set data = load_setup_py_data() %}

package:
  name: pypsbuilder
  version: {{ data.get('version') }}

source:
  git_url: https://github.com/ondrolexa/pypsbuilder.git
  git_rev: {{ data.get('version') }}

build:
  entry_points:
    - psbuilder = pypsbuilder.psbuilder:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - pyqt
    - numpy
    - matplotlib

  run:
    - python
    - pyqt
    - numpy
    - matplotlib

test:
  # Python imports
  imports:
    - pypsbuilder

about:
  home: https://github.com/ondrolexa/pypsbuilder
  license: GPL-3.0
  license_file: LICENSE
  summary: Simplistic THERMOCALC front-end for constructing PT pseudosections
  license_family: GPL
  doc_url: https://pypsbuilder.readthedocs.org
  dev_url: https://github.com/ondrolexa/pypsbuilder
