name: Python testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ['3.8', '3.9', '3.10']
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda
      - name: Install dependencies
        run: conda env update --file ci-environment.yml --name base
      - name: Lint with flake8
        run: flake8 . --exit-zero --max-complexity=20 --max-line-length=127 --ignore=E501,W503,C901
      - name: Test with pytest
        run: pytest -v